/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package nemostein.games.geocontact.theriot.assets.states.gameplay.hud.buttons
{
	import flash.display.Bitmap;
	
	[Embed(source="small3.up.png")]
	
	public class AssetStatesGameplayHudButtonsSmall3up extends Bitmap
	{
	
	}
}