/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package nemostein.games.geocontact.theriot.assets.upgradewheel
{
	import flash.display.Bitmap;
	
	[Embed(source="UpgradeWheelUnits.png")]
	
	public class AssetUpgradeWheelUnits extends Bitmap
	{
	
	}
}