/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package nemostein.games.geocontact.theriot.assets.states.gameplay.levelTest
{
	import flash.utils.ByteArray;
	
	[Embed(source="paths.paf",mimeType="application/octet-stream")]
	
	public class AssetStatesGameplayLevelTestPaths extends ByteArray
	{
	
	}
}