/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package nemostein.games.geocontact.theriot.assets.states.gameplay.levelTest
{
	import flash.display.Bitmap;
	
	[Embed(source="background.png")]
	
	public class AssetStatesGameplayLevelTestBackground extends Bitmap
	{
	
	}
}