/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package nemostein.games.geocontact.theriot.assets.states.gameplay.units
{
	import flash.display.Bitmap;
	
	[Embed(source="01.png")]
	
	public class AssetStatesGameplayUnits01 extends Bitmap
	{
	
	}
}