/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package nemostein.games.geocontact.theriot.assets.states.gameplay.hud.tabs
{
	import flash.display.Bitmap;
	
	[Embed(source="timer.png")]
	
	public class AssetStatesGameplayHudTabsTimer extends Bitmap
	{
	
	}
}