/**
 * File auto-generated by AS3 AssetsParser
 * NemoStein, 2012
 * http://www.nemostein.com.br
 */
package nemostein.games.geocontact.theriot.assets.states.gameplay.hud.controlBar
{
	import flash.display.Bitmap;
	
	[Embed(source="alliedEnd.png")]
	
	public class AssetStatesGameplayHudControlBarAlliedEnd extends Bitmap
	{
	
	}
}